from streamlit import (text_input, header, title, subheader, container, markdown, sidebar, link_button, divider, set_page_config)

title("Wir sind Autisten")
sidebar.page_link("app.py", label="Was ist Autismus?") 
sidebar.page_link("pages/app3.py", label="frühkindlicher Autismus und atypischer Autismus")
sidebar.page_link("pages/user.py", label="Asperger-Syndrom")
sidebar.page_link("pages/app4.py", label="Autismus und Schule")
sidebar.page_link("pages/app5.py", label="Autismus und Beruf")
sidebar.page_link("pages/app6.py", label="Diagnose und Therapie")
sidebar.page_link("pages/app7.py", label="Eltern von autistischen Kindern")
sidebar.page_link("pages/app8.py", label="Wie kann ich helfen?")
sidebar.page_link("pages/app9.py", label="Mehr über Autismus")
   
markdown(":star2: Vielfalt in der Welt:star2:")
markdown(":smile: Every autistic is unique :smile:")
divider()
header("Autismus und Schule")
import streamlit as st
st.image("https://static.bnn.de/karlsruhe/AdobeStock_322887633.jpeg-424avd/alternates/LANDSCAPE_16x9_BASE/AdobeStock_322887633.jpeg", caption="Autistic child in school", use_column_width=True)
subheader("Welche Schwierigkeiten haben autistische Kinder in der Schule?")
markdown("Autistische Kinder haben oft Schwierigkeiten in der Schule. Sie können sich schlecht konzentrieren, haben Probleme, sich zu organisieren und haben oft Schwierigkeiten, sich in der Klasse zu integrieren. Sie können auch Schwierigkeiten haben, soziale Kontakte zu knüpfen und Freundschaften zu schließen. Einige autistische Kinder haben auch Schwierigkeiten, mit Veränderungen umzugehen und haben oft Probleme, sich an neue Situationen anzupassen. Dies kann dazu führen, dass sie sich in der Schule unwohl fühlen und sich zurückziehen.")
divider()
subheader("Was können Lehrer tun, um autistischen Kindern zu helfen?")
markdown("Lehrer können autistischen Kindern helfen, indem sie auf ihre Bedürfnisse eingehen und ihnen Unterstützung anbieten. Sie können zum Beispiel darauf achten, dass der Unterricht strukturiert ist und klare Regeln und Erwartungen hat. Sie können auch darauf achten, dass die Kinder genügend Zeit haben, um sich auf neue Situationen vorzubereiten und sich anzupassen. Lehrer können auch darauf achten, dass die Kinder genügend Pausen haben, um sich zu erholen und sich zu entspannen. Sie können auch darauf achten, dass die Kinder genügend Zeit haben, um sich mit anderen Kindern auszutauschen und Freundschaften zu schließen. Lehrer können auch darauf achten, dass die Kinder genügend Zeit haben, um sich mit anderen Kindern auszutauschen und Freundschaften zu schließen.")
divider()
subheader("Mehr Informationen")
markdown("Wenn Sie mehr über Autismus und Schule erfahren möchten, können Sie auf den folgenden Link klicken:")
link_button("Schule", "https://www.autismus.de/was-ist-autismus/schule.html")

