from streamlit import (text_input, header, title, subheader, container, markdown, sidebar, link_button, divider, set_page_config)

title("Wir sind Autisten")
sidebar.page_link("app.py", label="Was ist Autismus?") 
sidebar.page_link("pages/app3.py", label="frühkindlicher Autismus und atypischer Autismus")
sidebar.page_link("pages/user.py", label="Asperger-Syndrom")
sidebar.page_link("pages/app4.py", label="Autismus und Schule")
sidebar.page_link("pages/app5.py", label="Autismus und Beruf")
sidebar.page_link("pages/app6.py", label="Diagnose und Therapie")
sidebar.page_link("pages/app7.py", label="Eltern von autistischen Kindern")
sidebar.page_link("pages/app8.py", label="Wie kann ich helfen?")
sidebar.page_link("pages/app9.py", label="Mehr über Autismus")
   
markdown(":star2: Vielfalt in der Welt:star2:")
markdown(":smile: Every autistic is unique :smile:")
divider()
header("Autismus und Beruf")
import streamlit as st
st.image("https://media2.karriere-suedwestfalen.de/media/general/images/354498/354499.png", caption="Berufe", use_column_width=True)
subheader("Welche Schwierigkeiten haben Autisten im Beruf?")
markdown("Um gesellschaftlich teilhaben zu können, imitieren viele autistische Menschen neurotypisches Verhalten. Diese Anpassung wird als „Masking“ bezeichnet. Dabei wird versucht sich möglichst nah an die neurotypische Norm anzupassen und autistische Auffälligkeiten zu unterdrücken. Typische Situationen werden vorab genau durchdacht und das „richtige“ Verhalten wie z.B. der passende Gesichtsausdruck, die geeignete Körpersprache oder Blickkontakt halten wird einstudiert. Kristina Meyer-Estorf, Autisti:in, Coach und Peer-Beraterin, beschreibt Masking im Berufsalltag als das Anziehen eines Mantels. Je nach Situation wird ein anderer Mantel angezogen, welcher eine Art Fahrplan für das richtige Verhalten vorgeben soll. Diese Zusammenstellung von Verhaltensweisen dient dabei als Selbstschutz, um nicht stigmatisiert und ausgegrenzt zu werden. Darüber hinaus dient es in sozialen Interaktionen als wichtige Orientierung. Allerdings kostet diese geistige Anpassung sehr viel Konzentration und Energie und kann negative Folgen wie z.B. psychische Begleiterkrankungen mit sich bringen. Auch kann Masking dazu führen, dass Autismus im Erwachsenenalter lange nicht diagnostiziert wird.")
markdown("Neben Masking ist auch die alltägliche Reizüberflutung im Berufsleben eine enorme Herausforderung für autistische Menschen und kann zu einer Überladung, dem sogenannten „Overload“ führen. Dabei stauen sich verschiedene Reize wie Straßenlärm, das Summen einer Biene, das Gespräch nebenan, die Werbung im Radio an und kumulieren sich bis sie ein lautes und undurchdringliches, ungefiltertes Getöse ergeben. Darüber hinaus können es auch Gefühle sein, die sich anstauen, oder zu viele zu schnell nacheinander gestellte Fragen. Viele Autist: innen reagieren darauf mit Unruhe, Rückzug oder Ohren zuhalten. Um sich vor dem Overload zu schützen bzw. aus diesem Zustand wieder herauszukommen, haben viele Autist:innen gelernt, sich selbst zu stimulieren z.B. durch monotones Singen, das Aufsagen von Reimen, Hin- und Herschaukeln, Drehen von Gegenständen usw. Auch äußere Reize wie das Auflegen eines kühlen Tuches können helfen. Die Folge eines Overloads ohne Rückzugsmöglichkeit kann eine Kernschmelze „Meltdown“ genannt sein, welche für Außenstehende wie ein Wutausbruch wirken kann.")
markdown("Um solchen Situationen vorzubeugen bzw. damit besser umzugehen, ist es für autistische Menschen im Job wichtig, den Arbeitsplatz so barrierefrei wie möglich zu gestalten.")
link_button(url="https://karriere.myability.jobs/karrieretipps/autismus", label="Mehr Informationen")
divider()
subheader("Welche Stärken haben Autisten im Beruf?")
markdown("All dies macht es für betroffene Personen natürlich schwer, in der Arbeitswelt Fuß zu fassen. Doch viele Autisten haben Talente und Fähigkeiten, die auf dem Arbeitsmarkt sehr gefragt sind. Natürlich sind diese individuell und so unterschiedlich, wie die Menschen selbst. Dennoch gibt es einige Stärken, die viele Autisten in verschiedener Ausprägung vorweisen können. Dazu gehören beispielsweise:")
markdown("-eine ungewöhnliche Denkweise, die zu innovativen Lösungsansätzen führen kann.")
markdown("-das rationale Treffen von Entscheidungen.")
markdown("-eine hohe Intelligenz und räumliche Logik.")
markdown("-ein überdurchschnittliches Erinnerungsvermögen.")
markdown("-Ehrlichkeit und Sensibilität.")
markdown("-eine hohe Motivation und Zuverlässigkeit.")
markdown("-eine gründliche und präzise Arbeitsweise.")
markdown("-ein sehr gutes Zahlenverständnis.")
markdown("-analytisches Denken.")
link_button(url="https://www.stellenanzeigen.de/careeasy/autisten-in-der-arbeitswelt-sde17884/", label="Mehr Informationen")
divider()   
subheader("Welche Berufe eignen sich für Autisten?")
markdown("Es gibt viele Berufe, die sich besonders für Autisten eignen. Dazu gehören beispielsweise:")
link_button(url="https://karriere.myability.jobs/karrieretipps/jobs-fuer-menschen-mit-autismus", label="Berufe für Autisten")
divider()
subheader("Mehr Informationen")
link_button(url="https://www.minnstate.edu/careerexploration/planningtools/interest-assessment/index.html", label="CAREERwise interest assessment")
link_button (url="https://www.16personalities.com/de", label="16 personalities")
