from streamlit import (text_input, header, title, subheader, container, markdown, sidebar, link_button, divider, set_page_config)

title("Wir sind Autisten")
sidebar.page_link("app.py", label="Was ist Autismus?") 
sidebar.page_link("pages/app3.py", label="frühkindlicher Autismus und atypischer Autismus")
sidebar.page_link("pages/user.py", label="Asperger-Syndrom")
sidebar.page_link("pages/app4.py", label="Autismus und Schule")
sidebar.page_link("pages/app5.py", label="Autismus und Beruf")
sidebar.page_link("pages/app6.py", label="Diagnose und Therapie")
sidebar.page_link("pages/app7.py", label="Eltern von autistischen Kindern")
sidebar.page_link("pages/app8.py", label="Wie kann ich helfen?")
sidebar.page_link("pages/app9.py", label="Mehr über Autismus")
   
markdown(":star2: Vielfalt in der Welt:star2:")
markdown(":smile: Every autistic is unique :smile:")

divider()
header("Eltern von autistischen Kindern")
import streamlit as st
st.image("https://autismus-kultur.de/wp-content/uploads/2018/12/eltern-von-autisten-jpg-webp-981x350.webp?ezimgfmt=ng:webp/ngcb1", caption="Eltern von autistischen Kindern", use_column_width=True)
subheader("Herausforderungen")
markdown("Eltern von autistischen Kindern stehen vor besonderen Herausforderungen. Sie müssen sich mit den Besonderheiten ihres Kindes auseinandersetzen und ihm helfen, sich in der Welt zurechtzufinden. Oftmals sind sie mit Vorurteilen und Unverständnis konfrontiert. Es ist wichtig, dass Eltern von autistischen Kindern sich über Autismus informieren und sich mit anderen Eltern austauschen. Es gibt zahlreiche Selbsthilfegruppen und Beratungsstellen, die Eltern von autistischen Kindern unterstützen.")
link_button("Übersichtkarte: Selbsthilfegruppen", "https://www.selbsthilfe-autismus.de/karte.html")
divider()
subheader("Tipps für Eltern")
markdown("Hier sind einige Tipps für Eltern von autistischen Kindern:")
markdown("1. Informieren Sie sich über Autismus und die Besonderheiten Ihres Kindes.")
markdown("2. Nehmen Sie sich Zeit für Ihr Kind und hören Sie ihm zu.")
markdown("3. Unterstützen Sie Ihr Kind dabei, sich in der Welt zurechtzufinden.")
markdown("4. Suchen Sie sich Unterstützung bei Selbsthilfegruppen und Beratungsstellen.")
markdown("5. Nehmen Sie sich Zeit für sich selbst und gönnen Sie sich Pausen.")
divider()   
header("Häufig gestellte Fragen")
subheader("Sollte ich mein Kind testen lassen?")
markdown("Wenn Sie den Verdacht haben, dass Ihr Kind autistisch ist, sollten Sie es von einem Facharzt für Kinder- und Jugendpsychiatrie oder einem Kinder- und Jugendpsychologen testen lassen. Eine frühzeitige Diagnose und Therapie können Ihrem Kind helfen, sich besser zu entwickeln und mit den Herausforderungen des Alltags besser zurechtzukommen.")
subheader("Sollte ich meinem Kind von der Diagnose erzählen?")
markdown("Es ist wichtig, dass Sie Ihrem Kind die Diagnose Autismus erklären, wenn es alt genug ist, um sie zu verstehen. Ihr Kind sollte wissen, dass es nicht allein ist und dass es Unterstützung bekommt. Es ist wichtig, dass Sie mit Ihrem Kind über Autismus sprechen und ihm erklären, was das für sein Leben bedeutet.")
subheader("Sollte ich andere Menschen über die Diagnose meines Kindes informieren?")
markdown("Es ist wichtig, dass Sie andere Menschen über die Diagnose Ihres Kindes informieren, damit sie Ihr Kind besser verstehen und unterstützen können. Sie sollten mit Lehrern, Erziehern, Verwandten und Freunden über die Diagnose Ihres Kindes sprechen und ihnen erklären, wie sie Ihrem Kind helfen können.")
