from streamlit import (text_input, header, title, subheader, container, markdown, sidebar, link_button, divider, set_page_config)

title("Wir sind Autisten")
sidebar.page_link("app.py", label="Was ist Autismus?") 
sidebar.page_link("pages/app3.py", label="frühkindlicher Autismus und atypischer Autismus")
sidebar.page_link("pages/user.py", label="Asperger-Syndrom")
sidebar.page_link("pages/app4.py", label="Autismus und Schule")
sidebar.page_link("pages/app5.py", label="Autismus und Beruf")
sidebar.page_link("pages/app6.py", label="Diagnose und Therapie")
sidebar.page_link("pages/app7.py", label="Eltern von autistischen Kindern")
sidebar.page_link("pages/app8.py", label="Wie kann ich helfen?")
sidebar.page_link("pages/app9.py", label="Mehr über Autismus")
   
markdown(":star2: Vielfalt in der Welt:star2:")
markdown(":smile: Every autistic is unique :smile:")
divider()
header("Wie kann ich helfen?")
import streamlit as st
st.image("https://www.pommersche-diakonie.de/fileadmin/_processed_/3/4/csm_210602_Beratungsdienst_Autismus_2fb7f79dcc.jpg", caption="Wir sind im Spektrum", use_column_width=True)
subheader("wenn Sie einem autistischen Menschen helfen möchten, können Sie folgende Tipps beachten:")
markdown("1. Akzeptieren Sie die Besonderheiten des autistischen Menschen.")
markdown("2. Seien Sie geduldig und einfühlsam.")
markdown("3. Bieten Sie dem autistischen Menschen Hilfe an, wenn er sie benötigt.")
markdown("4. Zwingen Sie den autistischen Menschen nicht zu Dingen, die er nicht möchte.")
markdown("5. Informieren Sie sich über Autismus und die Bedürfnisse des autistischen Menschen.")
markdown("6. Fördern Sie die Stärken des autistischen Menschen.")
markdown("7. Seien Sie offen und ehrlich.")
markdown("8. Fragen Sie den autistischen Menschen, wenn Sie unsicher sind.")
markdown("9. Respektieren Sie die Grenzen des autistischen Menschen.")
markdown("10. Seien Sie breit, eine bunte Welt zu entdecken.")
link_button("Mehr Informationen", "https://www.enableme.de/de/artikel/vom-umgang-mit-autist-innen-1976")