from streamlit import (text_input, header, title, subheader, container, markdown, sidebar, link_button, divider, set_page_config)

title("Wir sind Autisten")
sidebar.page_link("app.py", label="Was ist Autismus?") 
sidebar.page_link("pages/app3.py", label="frühkindlicher Autismus und atypischer Autismus")
sidebar.page_link("pages/user.py", label="Asperger-Syndrom")
sidebar.page_link("pages/app4.py", label="Autismus und Schule")
sidebar.page_link("pages/app5.py", label="Autismus und Beruf")
sidebar.page_link("pages/app6.py", label="Diagnose und Therapie")
sidebar.page_link("pages/app7.py", label="Eltern von autistischen Kindern")
sidebar.page_link("pages/app8.py", label="Wie kann ich helfen?")
sidebar.page_link("pages/app9.py", label="Mehr über Autismus")
   
markdown(":star2: Vielfalt in der Welt:star2:")
markdown(":smile: Every autistic is unique :smile:")
divider()
header("Asperger-Syndrom")
import streamlit as st
st.image("https://iacc.hhs.gov/images/resources/categories/about-autism-wide.jpg", caption="fröhliche Kinder")
markdown("Das Asperger-Syndrom und der frühkindliche Autismus unterscheiden sich im Wesentlichen durch ihre Entwicklung. Die kommunikativen und sprachlichen Fähigkeiten von Kindern mit Asperger-Syndrom sind im Gegensatz zu Patienten mit frühkindlichem Autismus - in den ersten drei Lebensjahren unauffällig. Erste Schritte zum Selbstständigwerden und die Neugier an ihrer Umgebung sind vorhanden. Die motorische Entwicklung tritt zum Teil verzögert ein. Diese Form des Autismus wird daher meist erst im Vorschul- oder Schulalter deutlich. Obwohl die Kinder oft durchschnittlich intelligent sind, haben sie häufig in Kindergarten und Schule Schwierigkeiten. Sie weisen eine gestörte soziale Interaktion und stereotype Verhaltensmuster auf – in vielen Fällen aber schwächer ausgeprägt als beim frühkindlichen Autismus. In der Regel zeigen sich diese Auffälligkeiten beim gemeinsamen Spielen mit gleichaltrigen Kindern, an dem Kinder mit Asperger Syndrom entweder kein Interesse haben oder es nach eigenen Regeln spielen wollen, so dass es oft zu Streit kommt. In bestimmten Wissensbereichen, die das Allgemeinwissen deutlich dominieren, können Personen mit Asperger Syndrom häufig erstaunliche Fähigkeiten, Kenntnisse und Gedächtnisleistungen zeigen (Inselbegabung). ")
markdown("Fachliche Unterstützung: Prof. Dr. med. Dipl. Theol. Christine M. Freitag, Frankfurt (DGKJP)")
markdown("Quelle: https://www.kinderaerzte-im-netz.de/krankheiten/autismus/asperger-syndrom/")
divider()
subheader("Online Test")
markdown("Möchtest du wissen, ob du das Asperger-Syndrom hast? Dann mache diesen Test:")
link_button(url="http://www.rdos.net/eng/", label="ASPIE-QUIZ")